-- Bendito Café - Sprint 6: alinhamento com Cardápio BC 2025
-- Rode este SQL no Supabase depois de subir os arquivos da Sprint 6.
-- Ele sincroniza nomes, descrições, preços e imagens usados pela função segura create_public_order.

insert into public.products (id, name, description, price, group_name, subgroup, badge, image_url, active)
values
  ('cafe-coado', 'Café Coado', 'Café coado tradicional.', 6.00, 'bebidas-quentes', 'com-cafe', 'Com café', 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?q=80&w=1200&auto=format&fit=crop', true),
  ('expresso', 'Expresso', 'Uma dose de café expresso.', 7.00, 'bebidas-quentes', 'com-cafe', 'Com café', 'https://images.unsplash.com/photo-1510707577719-ae7c14805e3a?q=80&w=1200&auto=format&fit=crop', true),
  ('expresso-duplo', 'Expresso Duplo', 'Duas doses de café expresso.', 8.50, 'bebidas-quentes', 'com-cafe', 'Com café', 'https://images.unsplash.com/photo-1510707577719-ae7c14805e3a?q=80&w=1200&auto=format&fit=crop', true),
  ('cappuccino-italiano', 'Cappuccino Italiano', 'Café expresso com leite.', 10.00, 'bebidas-quentes', 'com-cafe', 'Clássico', 'assets/img/produtos/cappuccino-italiano.jpeg', true),
  ('cappuccino-cremoso', 'Cappuccino Cremoso', 'Mistura para cappuccino e leite.', 12.00, 'bebidas-quentes', 'com-cafe', 'Cremoso', 'assets/img/produtos/cappuccino-cremoso.jpeg', true),
  ('cafe-prensa-francesa', 'Café na Prensa Francesa', 'Café coado na Prensa Francesa.', 11.00, 'bebidas-quentes', 'com-cafe', 'Com café', 'https://images.unsplash.com/photo-1498804103079-a6351b050096?q=80&w=1200&auto=format&fit=crop', true),
  ('expresso-com-chantilly', 'Expresso com Chantilly', 'Café expresso duplo com chantilly.', 12.00, 'bebidas-quentes', 'com-cafe', 'Especial', 'assets/img/produtos/expresso-com-chantilly.jpeg', true),
  ('affogato', 'Affogato', 'Café expresso e sorvete.', 13.00, 'bebidas-quentes', 'com-cafe', 'Sobremesa', 'assets/img/produtos/affogato.jpeg', true),
  ('mocha', 'Mocha', 'Café expresso, leite e chocolate.', 15.00, 'bebidas-quentes', 'com-cafe', 'Chocolate', 'assets/img/produtos/mocha.jpeg', true),
  ('super-mocha', 'Super Mocha', 'Café expresso, leite, chocolate e canela.', 16.00, 'bebidas-quentes', 'com-cafe', 'Premium', 'assets/img/produtos/super-mocha.jpeg', true),
  ('cappuccino-gourmet', 'Cappuccino Gourmet', 'Mistura para cappuccino, leite, borda de creme de avelã e chantilly.', 18.00, 'bebidas-quentes', 'com-cafe', 'Gourmet', 'assets/img/produtos/cappuccino-gourmet.jpeg', true),
  ('cha-matte-quente', 'Chá Matte', 'Sabores: tradicional, limão, pêssego, gengibre, canela e tangerina.', 11.00, 'bebidas-quentes', 'sem-cafe', 'Sem café', 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?q=80&w=1200&auto=format&fit=crop', true),
  ('chocolate-cremoso', 'Chocolate Cremoso', 'Mistura para chocolate e leite.', 12.00, 'bebidas-quentes', 'sem-cafe', 'Sem café', 'https://images.unsplash.com/photo-1517578239113-b03992dcdd25?q=80&w=1200&auto=format&fit=crop', true),
  ('chocolate-europeu', 'Chocolate Europeu', 'Mistura para chocolate e leite. Chocolate mais grosso.', 15.00, 'bebidas-quentes', 'sem-cafe', 'Sem café', 'https://images.unsplash.com/photo-1542990253-a781e04c0082?q=80&w=1200&auto=format&fit=crop', true),
  ('chai-latte', 'Chai Latte', 'Xarope de Chai e leite.', 18.00, 'bebidas-quentes', 'sem-cafe', 'Sem café', 'assets/img/produtos/chai-latte.jpeg', true),
  ('cappuccino-gelado', 'Cappuccino', 'Mistura para cappuccino, leite e gelo.', 13.90, 'bebidas-geladas', 'com-cafe', 'Gelado', 'assets/img/produtos/cappuccino-gelado.jpeg', true),
  ('americano-gelado', 'Americano Gelado', 'Café expresso duplo, água, leite, macadâmia e gelo.', 16.00, 'bebidas-geladas', 'com-cafe', 'Gelado', 'assets/img/produtos/americano-gelado.jpeg', true),
  ('frapuccino-menta-e-chocolate', 'Frappuccino Menta e Chocolate', 'Café expresso, leite, menta, calda de chocolate e gelo.', 17.00, 'bebidas-geladas', 'com-cafe', 'Gelado', 'assets/img/produtos/frapuccino-menta-e-chocolate.jpeg', true),
  ('chococcino', 'Chococcino', 'Mistura para cappuccino e chocolate, ovomaltine, leite e gelo.', 18.00, 'bebidas-geladas', 'com-cafe', 'Chocolate', 'assets/img/produtos/chococcino.jpeg', true),
  ('expresso-com-tonica', 'Expresso com Tônica', 'Café expresso duplo, água tônica, xarope e gelo. Sabores: gengibre, pêssego, avelã, caramelo salgado e baunilha.', 18.00, 'bebidas-geladas', 'com-cafe', 'Refrescante', 'assets/img/produtos/expresso-com-tonica.jpeg', true),
  ('frapuccino-super-mocha', 'Frappuccino Super Mocha', 'Café expresso, leite, macadâmia, canela, calda de chocolate, chantilly e gelo.', 18.00, 'bebidas-geladas', 'com-cafe', 'Mocha', 'assets/img/produtos/frapuccino-super-mocha.jpeg', true),
  ('cappuccino-frozen', 'Cappuccino Frozen', 'Mistura para cappuccino, leite, sorvete de creme, caramelo salgado e gelo.', 22.00, 'bebidas-geladas', 'com-cafe', 'Frozen', 'assets/img/produtos/cappuccino-frozen.jpeg', true),
  ('cha-matte-gelado', 'Chá Matte', 'Sabores: tradicional, limão, pêssego, gengibre, canela e tangerina.', 12.00, 'bebidas-geladas', 'sem-cafe', 'Sem café', 'assets/img/produtos/cha-matte-gelado.jpeg', true),
  ('soda-italiana', 'Soda Italiana', 'Água com gás, xarope e gelo. Sabores: maçã verde, gengibre, menta, cranberry, coco, tangerina, grenadine, morango e limão.', 13.00, 'bebidas-geladas', 'sem-cafe', 'Sem café', 'assets/img/produtos/soda-italiana.jpeg', true),
  ('chocolate-gelado', 'Chocolate', 'Mistura para chocolate, leite e gelo.', 13.90, 'bebidas-geladas', 'sem-cafe', 'Sem café', 'assets/img/produtos/chocolate-gelado.jpeg', true),
  ('pink-lemonade', 'Pink Limonade', 'Purê de morango, suco de limão taiti e gelo.', 15.00, 'bebidas-geladas', 'sem-cafe', 'Sem café', 'assets/img/produtos/pink-lemonade.jpeg', true),
  ('chai-latte-gelado', 'Chai Latte', 'Xarope de Chai, leite e gelo.', 18.00, 'bebidas-geladas', 'sem-cafe', 'Sem café', 'assets/img/produtos/chai-latte-gelado.jpeg', true),
  ('mat-01', 'Matcha Puro', 'Matcha e água.', 11.00, 'matcha', 'quente', 'Quente', 'assets/img/produtos/matcha-puro.jpeg', true),
  ('mat-02', 'Latte Matcha', 'Matcha, leite e coco.', 15.00, 'matcha', 'quente', 'Quente', 'assets/img/produtos/latte-matcha.jpeg', true),
  ('mat-03', 'Latte Matcha com Morango', 'Matcha, leite, purê de morango e gelo.', 18.00, 'matcha', 'gelado', 'Gelado', 'assets/img/produtos/latte-matcha-com-morango.jpeg', true),
  ('mat-04', 'Latte Matcha com Coco e Menta', 'Matcha, leite, coco, menta e gelo.', 18.00, 'matcha', 'gelado', 'Gelado', 'assets/img/produtos/latte-matcha-com-coco-e-menta.jpeg', true),
  ('mat-05', 'Matcha Tropical', 'Matcha, água com gás, gengibre, pêssego e gelo.', 18.00, 'matcha', 'gelado', 'Tropical', 'assets/img/produtos/matcha-tropical.jpeg', true),
  ('out-01', 'Água', 'Sem gás ou com gás.', 5.00, 'outras-bebidas', 'todos', 'Clássico', 'https://images.unsplash.com/photo-1564419439288-b2d15a86f8ff?q=80&w=1200&auto=format&fit=crop', true),
  ('out-02', 'Sucos de Polpa', 'Consultar sabores do dia.', 9.00, 'outras-bebidas', 'todos', 'Consultar', 'https://images.unsplash.com/photo-1622597467836-f3285f2131b8?q=80&w=1200&auto=format&fit=crop', true),
  ('out-03', 'Coca-Cola 200ml', 'Gelado.', 5.00, 'outras-bebidas', 'todos', 'Gelado', 'https://images.unsplash.com/photo-1581636625402-29b2a704ef13?q=80&w=1200&auto=format&fit=crop', true),
  ('add-01', 'Leite sem Lactose', 'Adicional para adaptar a bebida.', 1.50, 'adicionais', 'todos', 'Adicional', 'https://images.unsplash.com/photo-1550583724-b2692b85b150?q=80&w=1200&auto=format&fit=crop', true),
  ('add-02', 'Ovomaltine', 'Adicional crocante para enriquecer bebidas e sobremesas.', 3.00, 'adicionais', 'todos', 'Extra', 'assets/img/produtos/ovomaltine.jpeg', true),
  ('add-03', 'Chantilly', 'Cobertura adicional.', 3.00, 'adicionais', 'todos', 'Extra', 'assets/img/produtos/chantilly.jpeg', true),
  ('add-04', 'Leite Vegetal', 'Opção vegetal para bebidas.', 4.00, 'adicionais', 'todos', 'Adicional', 'https://images.unsplash.com/photo-1550583724-b2692b85b150?q=80&w=1200&auto=format&fit=crop', true),
  ('add-05', 'Borda', 'Doce de leite ou creme de avelã.', 5.00, 'adicionais', 'todos', 'Doce', 'assets/img/produtos/borda.jpeg', true),
  ('doc-01', 'Bendito Bolinho', 'Mini bolo com cobertura de ganache de chocolate. Consultar sabores.', 13.00, 'doces', 'todos', 'Vitrine', 'assets/img/produtos/bendito-bolinho.png', true),
  ('doc-02', 'Pão Casadinho', '2 fatias de pão francês: uma fatia de queijo e requeijão e a outra fatia doce com creme de avelã, doce de leite ou goiabada.', 13.00, 'doces', 'todos', 'Doce', 'assets/img/produtos/pao-casadinho.png', true),
  ('doc-03', 'Pão de Minas', '2 fatias de pão francês, recheado com cream cheese, doce de leite e queijo de minas.', 18.00, 'doces', 'todos', 'Especial', 'assets/img/produtos/pao-de-minas.png', true),
  ('doc-04', 'Croissant com Creme de Avelã', 'Croissant de chocolate coberto com creme de avelã.', 18.00, 'doces', 'todos', 'Queridinho', 'assets/img/produtos/croissant-de-avela.png', true),
  ('doc-05', 'Brownie', 'Brownie tradicional.', 10.00, 'doces', 'todos', 'Clássico', 'assets/img/produtos/brownie.png', true),
  ('doc-06', 'Brownie com Sorvete', 'Brownie tradicional com bola de sorvete de creme.', 16.00, 'doces', 'todos', 'Destaque', 'assets/img/produtos/brownie-com-sorvete.png', true),
  ('sal-01', 'Waffle', 'Waffle de massa de pão de queijo.', 7.00, 'salgados', 'todos', 'Massa pão de queijo', 'assets/img/produtos/waffle.png', true),
  ('sal-02', 'Waffle Recheado', 'Waffle de massa de pão de queijo. Sabores: presunto e queijo, creme de avelã, doce de leite e mel.', 12.00, 'salgados', 'todos', 'Sabores', 'assets/img/produtos/waffle-recheado.png', true),
  ('sal-03', '4 Mini Empadas', 'Consultar sabores do dia.', 10.00, 'salgados', 'todos', 'Consultar', 'assets/img/produtos/mini-empadas.png', true),
  ('sal-04', 'Assados', 'Croissant e outros. Consultar sabores do dia.', 12.00, 'salgados', 'todos', 'Do dia', 'assets/img/produtos/croissant.png', true),
  ('sal-05', 'Empada', 'Consultar sabores do dia.', 13.00, 'salgados', 'todos', 'Do dia', 'assets/img/produtos/empada-tradicional.png', true),
  ('lan-01', 'Pão com Manteiga', 'Fatia de pão caseiro com manteiga.', 7.00, 'lanches', 'na-chapa', 'Na chapa', 'assets/img/produtos/pao-com-manteiga.png', true),
  ('lan-02', 'Pão com Manteiga, Mel e Orégano', 'Fatia de pão caseiro com manteiga, mel e orégano.', 11.00, 'lanches', 'na-chapa', 'Na chapa', 'assets/img/produtos/pao-com-manteiga-mel-e-oregano.png', true),
  ('lan-03', 'Pão com Ovo', 'Pão francês, ovo e requeijão.', 13.00, 'lanches', 'na-chapa', 'Café da manhã', 'assets/img/produtos/pao-com-ovo.png', true),
  ('lan-04', 'Misto Quente', 'Pão francês, requeijão, presunto e muçarela.', 13.00, 'lanches', 'na-chapa', 'Clássico', 'assets/img/produtos/misto-quente.png', true),
  ('lan-05', 'Bauru', 'Pão francês, requeijão, presunto, muçarela, tomate e orégano.', 14.00, 'lanches', 'na-chapa', 'Querido', 'assets/img/produtos/bauru.png', true),
  ('lan-06', 'Bauru com Ovo', 'Pão francês, requeijão, presunto, muçarela, ovo, tomate e orégano.', 17.00, 'lanches', 'na-chapa', 'Completo', 'assets/img/produtos/bauru-com-ovo.png', true),
  ('lan-07', 'Sanduiche Natural', 'Pão integral, patê de frango, alface e tomate.', 20.00, 'lanches', 'na-chapa', 'Leve', 'https://images.unsplash.com/photo-1528736235302-52922df5c122?q=80&w=1200&auto=format&fit=crop', true),
  ('lan-08', 'Omelete', 'Ovos, tomate, presunto, muçarela e orégano.', 21.00, 'lanches', 'na-chapa', 'Forte', 'https://images.unsplash.com/photo-1510693206972-df098062cb71?q=80&w=1200&auto=format&fit=crop', true),
  ('lan-09', 'Bacon & Ovo', 'Fatia de pão caseiro, requeijão, ovo mexido, bacon e muçarela.', 22.00, 'lanches', 'na-chapa', 'Destaque', 'assets/img/produtos/bacon-e-ovo.png', true),
  ('combo-primeiro-tempo', 'Combo 1º Tempo', 'Cappuccino gelado + Pão com Ovo para entrar no clima do jogo.', 29.00, 'combos-torcida', 'copa2026', 'Copa 2026', 'https://images.unsplash.com/photo-1505575967455-40e256f73376?q=80&w=1200&auto=format&fit=crop', true),
  ('combo-torcida-dupla', 'Combo Torcida Dupla', '2 bebidas geladas + 2 salgados para acompanhar o jogo com companhia.', 64.00, 'combos-torcida', 'copa2026', 'Mais pedido', 'https://images.unsplash.com/photo-1517747614396-d21a78b850e8?q=80&w=1200&auto=format&fit=crop', true),
  ('combo-intervalo-doce', 'Combo Intervalo Doce', 'Brownie com Sorvete + bebida gelada para adoçar o intervalo.', 35.00, 'combos-torcida', 'copa2026', 'Doce', 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?q=80&w=1200&auto=format&fit=crop', true),
  ('combo-mesa-da-torcida', 'Combo Mesa da Torcida', 'Porção maior para mesa: bebidas, salgados e doce para dividir.', 119.00, 'combos-torcida', 'copa2026', 'Grupo', 'https://images.unsplash.com/photo-1527529482837-4698179dc6ce?q=80&w=1200&auto=format&fit=crop', true)
on conflict (id) do update set
  name = excluded.name,
  description = excluded.description,
  price = excluded.price,
  group_name = excluded.group_name,
  subgroup = excluded.subgroup,
  badge = excluded.badge,
  image_url = excluded.image_url,
  active = excluded.active,
  updated_at = now();
